In [3]:
%ls

__pycache__/       demo.ipynb         kokler.json        tr_tokenizer.py
bpe_tokenler.json  ekler.json         tr_decoder.py


In [1]:
from tr_tokenizer import TRTokenizer

tokenizer = TRTokenizer()

text = """
Ali Ata Bak▁ aliler ahmetler selmanlar da bizde onlar da testte kitapta kitabını okudum bu işe
 
 burnunu sokma
Burun buruna bir kaza\toldu
 """
ids = tokenizer.encode(text)
ids

[3,
 0,
 2697,
 2,
 0,
 2212,
 2,
 0,
 2794,
 1,
 2,
 18194,
 20043,
 2,
 6766,
 20000,
 2,
 17321,
 20000,
 2,
 20024,
 2,
 2595,
 20024,
 2,
 2627,
 2,
 20024,
 2,
 3045,
 20024,
 2,
 227,
 20024,
 2,
 227,
 15247,
 2,
 2656,
 10572,
 2,
 2503,
 2,
 2599,
 20038,
 3,
 3,
 2,
 165,
 20021,
 20035,
 2,
 20064,
 4373,
 20002,
 3,
 0,
 165,
 2,
 165,
 20037,
 2,
 2501,
 2,
 3303,
 4,
 2502,
 20026,
 3,
 2]

In [2]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-270m")
model = AutoModelForCausalLM.from_pretrained("google/gemma-3-270m")



In [ ]:
from gemma_model import GemmaForCausalLM, get_config_for_270m_tr_tokenizer

config_270m = get_config_for_270m_tr_tokenizer("float32")

gemma_model = GemmaForCausalLM(config_270m, tokenizer)
# gemma_model.load_weights_from_hf(model.model.state_dict())
gemma_model.from_pretrained("gemma-3-270m-tr-tokenizer")


'cartroundponzaşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşirazşiraz'

In [ ]:
gemma_model.generate("Merhaba, nasıl yardımcı olabilirim?")


'sismografsismografsismografsismografsismografoglemuamıslanmaıslanmasümüksütemlikkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkullnkulln'

In [5]:
import torch.nn as nn
gemma_model.embedder = nn.Embedding(32768, 640)

In [7]:
gemma_model

GemmaForCausalLM(
  (embedder): Embedding(32768, 640)
  (model): GemmaModel(
    (layers): ModuleList(
      (0-17): 18 x GemmaDecoderLayer(
        (self_attn): GemmaAttention(
          (q_proj): Linear(in_features=640, out_features=1024, bias=False)
          (k_proj): Linear(in_features=640, out_features=256, bias=False)
          (v_proj): Linear(in_features=640, out_features=256, bias=False)
          (o_proj): Linear(in_features=1024, out_features=640, bias=False)
          (query_norm): RMSNorm()
          (key_norm): RMSNorm()
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=640, out_features=2048, bias=False)
          (up_proj): Linear(in_features=640, out_features=2048, bias=False)
          (down_proj): Linear(in_features=2048, out_features=640, bias=False)
        )
        (input_layernorm): RMSNorm()
        (post_attention_layernorm): RMSNorm()
        (pre_feedforward_layernorm): RMSNorm()
        (post_feedforward_layernorm): RMSNorm()
   

In [6]:
gemma_model.save_pretrained("gemma-3-270m-tr-tokenizer")

In [11]:
import torch
tensors = tokenizer.encode("Merhaba, nasıl yardımcı olabilirim?")
tensors = torch.tensor(tensors)
tensors = tensors.unsqueeze(0)
tensors = tensors.to("cpu")

ids = model.generate(tensors)
ids

tensor([[     2,  79636, 236764,  56921, 118097,  85310,    548, 236881,    107,
         104469, 164694, 236764,  39152,  40611,   3482,  41753, 169890,   7908,
         236761,    108,    206,   2060,    520,    107,    215,    108, 236776,
           1831]])

In [12]:
tokenizer.decode(ids[0])

'<bos>Merhaba, nasıl yardımcı olabilirim?\nSoruyorum, ilk önce bir şekilde yazdım.\n\n<code>return m\n</code>\n\nAral'

In [ ]:
model_1b = AutoModelForCausalLM.from_pretrained("google/gemma-3-1b-pt")
model_1b

In [2]:
tokenizer.eos_token_id

1

In [ ]:
model.model.save_pretrained("gemma-3-270m")

In [7]:
model.model.state_dict().keys()


odict_keys(['embed_tokens.weight', 'layers.0.self_attn.q_proj.weight', 'layers.0.self_attn.k_proj.weight', 'layers.0.self_attn.v_proj.weight', 'layers.0.self_attn.o_proj.weight', 'layers.0.self_attn.q_norm.weight', 'layers.0.self_attn.k_norm.weight', 'layers.0.mlp.gate_proj.weight', 'layers.0.mlp.up_proj.weight', 'layers.0.mlp.down_proj.weight', 'layers.0.input_layernorm.weight', 'layers.0.post_attention_layernorm.weight', 'layers.0.pre_feedforward_layernorm.weight', 'layers.0.post_feedforward_layernorm.weight', 'layers.1.self_attn.q_proj.weight', 'layers.1.self_attn.k_proj.weight', 'layers.1.self_attn.v_proj.weight', 'layers.1.self_attn.o_proj.weight', 'layers.1.self_attn.q_norm.weight', 'layers.1.self_attn.k_norm.weight', 'layers.1.mlp.gate_proj.weight', 'layers.1.mlp.up_proj.weight', 'layers.1.mlp.down_proj.weight', 'layers.1.input_layernorm.weight', 'layers.1.post_attention_layernorm.weight', 'layers.1.pre_feedforward_layernorm.weight', 'layers.1.post_feedforward_layernorm.weight',

In [18]:
model.model.embed_tokens.weight[0][:10]

tensor([-0.0073,  0.0430, -0.0342, -0.0210, -0.0120,  0.0289,  0.0051, -0.0322,
         0.0381, -0.0128], grad_fn=<SliceBackward0>)

In [19]:
model.lm_head.weight[0][:10]

tensor([-0.0073,  0.0430, -0.0342, -0.0210, -0.0120,  0.0289,  0.0051, -0.0322,
         0.0381, -0.0128], grad_fn=<SliceBackward0>)

Missing keys: ['local_freqs_cis', 'global_freqs_cis']...
Successfully loaded 236 weights


In [2]:
gemma_model.generate("Merhaba, nasıl yardımcı olabilirim?")

IndexError: list index out of range